# See https://pre-commit.com/ for usage and config
repos:
  - repo: local
    hooks:

      - id: black
        args: [ "--line-length", "100" ]
        name: black
        stages: [ commit ]
        language: system
        entry: black
        types: [ python ]

      - id: pyupgrade
        name: pyupgrade
        stages: [ commit ]
        language: system
        entry: pyupgrade
        types: [ python ]

#      - id: pytest
#        name: pytest
#        stages: [ commit ]
#        language: system
#        entry: pipenv run pytest -x
#        types: [ python ]